language: cpp
cache: ccache


jobs:
  include:
    - os: linux
      dist: noble
      env: TARGET="linux64"
      compiler: gcc
      cache:
        directories:
          - ~/.ccache
        before_cache:
          - rm -f ~/.cache/*.log

    - os: osx
      osx_image: xcode15.4
      env: TARGET="osx"
      compiler:
        - clang

before_install:
  - if [ "$TARGET" == "linux64" ]; then
      sudo apt-get update;
    fi

  - if [ "$TARGET" == "osx" ]; then
      brew update;
    fi

install:
  - if [ "$TARGET" == "linux64" ]; then
      sudo apt-get install -y
      qt6-base-dev qt6-tools-dev qt6-multimedia-dev
      libqt6opengl6-dev libqt6openglwidgets6
      ccache;
    fi

  - if [ "$TARGET" == "osx" ]; then
      brew install qt ccache;
      export PATH="$(brew --prefix qt)/bin:$PATH";
      export PATH="/usr/local/opt/ccache/libexec:$PATH";
    fi

before_script:
  - if [ "$TARGET" == "osx" ]; then
      app="MapMap.app";
    fi

script:
  - ccache -z
  - ccache -s
  - if [ "$TARGET" == "linux64" ]; then
      qmake6 mapmap.pro;
      make -j4;
    fi

  - if [ "$TARGET" == "osx" ]; then
      qmake -config release;
      make -j4;
    fi
  - ccache -s
