version: '{branch}-{build}'

build:
  verbosity: minimal

environment:
  matrix:
    - BUILD: 'Release'
      CONFIG: debug

install:
  - set QTDIR=C:\Qt\6.8.0\mingw_64
  - set PATH=%PATH%;%QTDIR%\bin;C:\mingw64\bin

build_script:
  - qmake mapmap.pro
  - mingw32-make
