#!/bin/sh

# update CONTRIBUTORS.md based on git history.

# git log --reverse --format='%aN (%aE)' | perl -we '
# BEGIN {
# 	%seen = (), @authors = ();
# }
# while (<>) {
# 	next if $seen{$_};
# 	$seen{$_} = push @authors, "- ", $_;
# 
# }
# END {
# 	print "## Contributors\n\n";
#     print "#### Ordered by first contribution.\n\n";
# 	print @authors, "\n";
# 	print "#### Generated by scripts/update-contributors.sh.\n";
# }
# ' > ../docs/informations/CONTRIBUTORS.md

echo "Please update docs/informations/CONTRIBUTORS.md by hand"

# Convert markdown file to html
markdown docs/informations/CONTRIBUTORS.md > docs/informations/CONTRIBUTORS.html
