[package]
name = "mapmap-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
mapmap-core = { path = "../mapmap-core" }
mapmap-render = { path = "../mapmap-render" }
imgui = { workspace = true }
imgui-wgpu = { workspace = true }
imgui-winit-support = { workspace = true }
wgpu = { workspace = true }
# Use winit 0.27 for imgui compatibility
winit = { version = "0.27", features = ["x11", "wayland"] }
