# Build MapMap on macOS with Qt 6
name: Build on macOS

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew install qt

    - name: Configure with qmake
      run: |
        export PATH="$(brew --prefix qt)/bin:$PATH"
        qmake mapmap.pro CONFIG+=release

    - name: Build
      run: |
        export PATH="$(brew --prefix qt)/bin:$PATH"
        make -j$(sysctl -n hw.logicalcpu)

    - name: Build and run tests
      run: |
        export PATH="($brew --prefix=qt)/bin:$PATH"
        cd tests/
        qmake6 tests.pro
        make -j$(sysctl -n hw.logicalcpu)
        QT_QPA_PLATFORM=offscreen make check
